# Generated by Django 2.1.1 on 2018-12-28 03:23

from django.db import migrations, models
import image.models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0008_auto_20181228_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=image.models.user_directory_path),
        ),
    ]
