# Generated by Django 2.1.1 on 2018-12-28 03:48

from django.db import migrations, models
import image.models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0009_auto_20181228_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='url_height',
            field=models.PositiveIntegerField(default=75),
        ),
        migrations.AddField(
            model_name='image',
            name='url_width',
            field=models.PositiveIntegerField(default=75),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(height_field='url_height', upload_to=image.models.user_directory_path, width_field='url_width'),
        ),
    ]
