# Generated by Django 2.1.1 on 2018-12-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0011_auto_20181228_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(upload_to='images/%Y/%m/%d'),
        ),
    ]
