# Generated by Django 2.1.1 on 2018-12-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0012_auto_20181228_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='test/%Y/%m/%d'),
        ),
    ]
