# Generated by Django 2.1.1 on 2018-12-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0014_auto_20181228_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(height_field='url_height', upload_to='images/%Y/%m/%d', width_field='url_width'),
        ),
    ]
