# Generated by Django 2.1.1 on 2018-12-28 06:36

from django.db import migrations, models
import image.models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0015_auto_20181228_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(height_field='url_height', upload_to=image.models.user_directory_path, width_field='url_width'),
        ),
    ]
